TA_FEATURE_PREFIX = "TA" #prefix technical features - should be TA
LABEL_FEATURE_PREFIX = "LB" #prefix for infromational features (currency, sector, industry, country)
COLUMNS_LAGGED_FILE = "cols_with_lags.pickle"
ML_DATA_FILE = "ml_data.csv" #file used for training, validation and predictions
INDICATOR_STATIC = "STATIC"
INDICATOR_DYAMIC = "DYNAMIC"
TRANSFORMATION_BIN = "bin"
TRANSFORMATION_ZSCORE = "zscore"
TRANSFORMATION_RANK = "rank"
